# SPDX-License-Identifier: LGPL-3.0-only
#
# Copyright (C) 2026 Corey Pennycuff
#
# This file is part of Ghoti.io Font.
#
# Ghoti.io Font is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License version 3 as
# published by the Free Software Foundation.
"""The layout fixtures: fonts whose `GSUB` and `GPOS` hold one of every lookup.

Imported by `make_fixtures.py` and run in the same pinned image. What these are
for is the part of the shaping engine a real font reaches only by accident: the
real population (the fonts in the oracle image) is mostly Latin kerning and
ligatures, which exercises pair adjustment, ligatures and a few contexts. A font
that has *every* lookup type and format - a context in all three formats, a chain
in all three, an alternate, a multiple that deletes, a reverse chain, a lookup
behind an extension, a cursive attachment, a mark on a ligature's second
component - is a font whose lines cover the code the corpus does not.

Two ways of writing a lookup, chosen by what fontTools will emit:

  * **feaLib**, for what a feature file can say: the formats it picks are the
    ones a font editor would produce, and the file is the readable statement of
    what the font does;
  * **`otTables` directly**, for the formats it will not emit (a context in
    format 1 or 2, a chain in format 2, a multiple substitution to nothing),
    which are in the specification and in real fonts.

Each fixture comes with a **cases file** (`*.shape`): one line per run to shape,
as `script<TAB>language<TAB>features<TAB>location<TAB>code points<TAB>note`. Both the unit
suite and `tools/oracle/hb_diff.py` read it, so a case is written once and is
answered by this library, by HarfBuzz and, through `tests/data/golden/shape.txt`,
by HarfBuzz's recorded answer in a run with no container.
"""

from fontTools.feaLib.builder import addOpenTypeFeaturesFromString
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib.tables import otTables as ot

CASES_HEADER = """\
# Shaping cases for the font of the same name.
#
# Generated by tools/fixtures/layout_fixtures.py. One run per line, tab separated:
#   script  language  features  location  code points (hex, space separated)  note
# `-` means none. Features are HarfBuzz's syntax: +liga -kern salt=2 liga[1:3]; a
# location is `tag=value,...` in user coordinates, as `--variations` takes it.
"""


def box(width, height=600, inset=60):
    """A rectangle the width of the glyph: a layout fixture draws nothing clever."""
    pen = TTGlyphPen(None)
    if width <= 2 * inset:
        inset = 0
    pen.moveTo((inset, 0))
    pen.lineTo((width - inset, 0))
    pen.lineTo((width - inset, height))
    pen.lineTo((inset, height))
    pen.closePath()
    return pen.glyph()


def empty():
    return TTGlyphPen(None).glyph()


def build_font(mf, label, glyphs, advances, cmap, fea):
    """A TrueType font with these glyphs, this cmap and this feature file."""
    order = [".notdef", "space"] + list(glyphs)
    widths = {".notdef": 600, "space": 300}
    widths.update(advances)
    shapes = {}
    for name in order:
        if name == "space":
            shapes[name] = empty()
        else:
            shapes[name] = box(widths.get(name, 500))
    mapping = {0x20: "space"}
    mapping.update(cmap)
    subtables = [mf.subtable(4, 0, 3, mapping), mf.subtable(4, 3, 1, mapping)]
    fb = mf.truetype(label, subtables, order=order, glyphs=shapes,
                     advances=widths)
    addOpenTypeFeaturesFromString(fb.font, fea)
    return fb


def cases_text(cases):
    """The cases file: header, then each case's line."""
    lines = [CASES_HEADER.rstrip("\n")]
    for case in cases:
        script, language, features, codepoints, note = case[:5]
        location = case[5] if len(case) > 5 else None
        lines.append("\t".join([
            script or "-", language or "-", features or "-", location or "-",
            " ".join("%04X" % c for c in codepoints), note]))
    return "\n".join(lines) + "\n"


def text(string):
    """The code points of a string, so a case reads as the text it shapes."""
    return [ord(c) for c in string]


# --- GSUB ----------------------------------------------------------------

GSUB_GLYPHS = (
    list("abcdefghijklmnopqrstuvwxyz")
    + ["a.alt1", "a.alt2", "a.alt3", "f_i", "f_f", "f_f_i", "f_l", "o_o",
       "acute", "grave", "ag"])

GSUB_ADVANCES = {n: 500 + 10 * i for i, n in enumerate(GSUB_GLYPHS)}
GSUB_ADVANCES.update({"f_i": 900, "f_f": 880, "f_f_i": 1300, "f_l": 910,
                      "o_o": 1100, "acute": 0, "grave": 0, "ag": 0})

GSUB_CMAP = {0x61 + i: c for i, c in enumerate("abcdefghijklmnopqrstuvwxyz")}
GSUB_CMAP[0x301] = "acute"
GSUB_CMAP[0x300] = "grave"

GSUB_FEA = """
languagesystem DFLT dflt;
languagesystem latn dflt;
languagesystem latn TRK;

@ACUTE = [acute];
@GRAVE = [grave];
@MARKS = [acute grave ag];

table GDEF {
    GlyphClassDef [a b c d e f g h i j k l m n o p q r s t u v w x y z a.alt1 a.alt2 a.alt3],
                  [f_i f_f f_f_i f_l o_o], @MARKS, ;
} GDEF;

# Single substitution: format 1 (one delta for all) and format 2 (a list).
feature ss01 { sub [a c e] by [b d f]; } ss01;
feature ss02 { sub [g k] by [x y]; } ss02;

# Multiple substitution, on by default through ccmp.
feature ccmp { sub h by h i; sub m by m m m; } ccmp;

# Alternate substitution; the feature's value picks the alternate.
feature salt { sub a from [a.alt1 a.alt2 a.alt3]; } salt;

# Ligatures, longest first as a font editor writes them.
feature liga {
    sub f f i by f_f_i;
    sub f f by f_f;
    sub f i by f_i;
    sub f l by f_l;
} liga;

# The same ligature under four lookup flags: which marks sit between o and o
# without stopping it.
feature dlig { lookupflag IgnoreMarks; sub o o by o_o; } dlig;
feature hlig { lookupflag 0; sub o o by o_o; } hlig;
feature cswh { lookupflag UseMarkFilteringSet @ACUTE; sub o o by o_o; } cswh;
feature cv01 { lookupflag MarkAttachmentType @GRAVE; sub o o by o_o; } cv01;

# Nested lookups, some of which change the length.
lookup L_xy { sub x by y; } L_xy;
lookup L_a2 { sub a by a a; } L_a2;
lookup L_b2x { sub b by x; } L_b2x;
lookup L_c3 { sub c by c c c; } L_c3;
lookup L_del { sub d by NULL; } L_del;

# A context with no backtrack or lookahead (GSUB type 5, format 3), applying
# three nested lookups of which the first and last grow the run.
feature ss03 { sub a' lookup L_a2 b' lookup L_b2x c' lookup L_c3; } ss03;

# A chain with context on both sides (type 6, format 3), one nested lookup.
feature ss04 { sub [a b] c' lookup L_c3 [d e]; } ss04;

# A chain in format 1 (glyph rules), two rules with different backtrack.
feature ss05 {
    sub p x' lookup L_xy q;
    sub r x' lookup L_xy q;
} ss05;

# Reverse chaining: substitutes backward, so each sees the original to its right.
feature ss06 { rsub p' q by z; } ss06;
feature ss07 { rsub [p q]' [q r] by [x y]; } ss07;

# A lookup behind an extension subtable.
lookup L_ext useExtension { sub [s t] by [u v]; } L_ext;
feature ss08 { lookup L_ext; } ss08;

# A ligature of two marks, under three lookup flags. After a ligature that had marks
# in it, those marks belong to its components, and whether a rule over them may reach
# across the ligature depends on whether the lookup skips ligatures.
feature ss15 { lookupflag 0; sub acute grave by ag; } ss15;
feature ss16 { lookupflag IgnoreLigatures; sub acute grave by ag; } ss16;
feature ss17 { lookupflag IgnoreMarks; sub acute grave by ag; } ss17;

# A ligature whose second component is a mark, in a lookup that skips marks: the
# mark is never one of the glyphs it can match, so it never forms.
feature ss25 { lookupflag IgnoreMarks; sub o acute by x; } ss25;

# A mark replaced by a base: the glyph is a base from then on, and takes room.
feature ss18 { sub acute by a; } ss18;

# A chain whose first input coverage does not hold the glyph it is tried on: the
# nested lookup would change an x, so it must not run.
feature ss19 { sub [a b] c' lookup L_xy [d e]; } ss19;

# Reverse chaining behind an extension subtable, which the loop that runs a lookup
# has to see through to know to run it backward.
lookup L_rext useExtension { rsub [p q]' [q r] by [x y]; } L_rext;
feature ss24 { lookup L_rext; } ss24;
"""

# Texts are the cases' code points; the notes say what each exercises.
GSUB_CASES = [
    # (script, language, features, text, note)
    ("latn", None, None, text("fi"), "ligature f_i"),
    ("latn", None, None, text("ffi"), "ligature f_f_i, longest first"),
    ("latn", None, None, text("ff"), "ligature f_f"),
    ("latn", None, None, text("fl"), "ligature f_l"),
    ("latn", None, None, text("ffl"), "f_f then l: no ffl ligature"),
    ("latn", None, None, text("office"), "ligature in a word"),
    ("latn", None, None, text("fif"), "ligature then a bare f"),
    ("latn", None, None, text("ffffi"), "ligatures in a run"),
    ("latn", None, "-liga", text("ffi"), "ligatures off"),
    ("latn", None, None, text("hm"), "multiple substitution, two and three glyphs"),
    ("latn", None, None, text("mhm"), "multiple substitution in a run"),
    ("latn", None, "-ccmp", text("hm"), "multiple substitution off"),
    ("latn", None, "+ss01", text("abcdef"), "single substitution, format 1"),
    ("latn", None, "+ss02", text("gkgk"), "single substitution, format 2"),
    ("latn", None, "+ss01,+ss02", text("aegk"), "two single substitutions"),
    ("latn", None, "+ss01[1:4]", text("aaaaa"), "a single substitution over a range"),
    ("latn", None, "salt=1", text("aaa"), "alternate 1"),
    ("latn", None, "salt=2", text("aba"), "alternate 2"),
    ("latn", None, "salt=3", text("a"), "alternate 3"),
    ("latn", None, "salt=4", text("a"), "alternate past the last: none"),
    ("latn", None, "+salt", text("a"), "alternate by a feature turned on"),
    ("latn", None, "+dlig", text("oo"), "ligature, IgnoreMarks"),
    ("latn", None, "+dlig", text("o") + [0x301] + text("o"), "IgnoreMarks over an acute"),
    ("latn", None, "+dlig", text("o") + [0x300, 0x301] + text("o"), "IgnoreMarks over two marks"),
    ("latn", None, "+hlig", text("o") + [0x301] + text("o"), "no flags: a mark stops it"),
    ("latn", None, "+hlig", text("oo") + [0x301], "a mark after the ligature"),
    ("latn", None, "+cswh", text("o") + [0x300] + text("o"), "mark filtering set: grave is outside the set"),
    ("latn", None, "+cswh", text("o") + [0x301] + text("o"), "mark filtering set: acute is in the set"),
    ("latn", None, "+cv01", text("o") + [0x301] + text("o"), "mark attachment type: acute is another class"),
    ("latn", None, "+cv01", text("o") + [0x300] + text("o"), "mark attachment type: grave is the class"),
    ("latn", None, "+ss03", text("abc"), "context, three nested lookups, growing the run"),
    ("latn", None, "+ss03", text("abcabc"), "context twice in a run"),
    ("latn", None, "+ss03", text("ab"), "context that does not match"),
    ("latn", None, "+ss04", text("acd"), "chain with both sides"),
    ("latn", None, "+ss04", text("bce"), "chain, other glyphs of the classes"),
    ("latn", None, "+ss04", text("cd"), "chain with no backtrack"),
    ("latn", None, "+ss05", text("pxq"), "chain format 1, first rule"),
    ("latn", None, "+ss05", text("rxq"), "chain format 1, second rule"),
    ("latn", None, "+ss05", text("sxq"), "chain format 1, no rule"),
    ("latn", None, "+ss06", text("pq"), "reverse chaining"),
    ("latn", None, "+ss07", text("ppqr"), "reverse chaining over a run"),
    ("latn", None, "+ss07", text("pqr"), "reverse chaining, both neighbours"),
    ("latn", None, "+ss08", text("stst"), "a lookup behind an extension"),
    ("latn", None, "+ss15", [0x301, 0x300], "a ligature of two marks"),
    ("latn", None, "+dlig,+ss15", text("o") + [0x301] + text("o") + [0x300],
        "marks between a ligature's components, then a rule over them: it may not reach across"),
    ("latn", None, "+dlig,+ss16", text("o") + [0x301] + text("o") + [0x300],
        "the same, in a lookup that skips ligatures"),
    ("latn", None, "+ss17", [0x301, 0x300], "marks are skipped, so a rule over marks never matches"),
    ("latn", None, "+ss25", text("o") + [0x301], "a rule over a mark in a lookup that skips marks never matches"),
    ("latn", None, "+ss18", text("o") + [0x301], "a mark replaced by a base is a base"),
    ("latn", None, "+ss19", text("axd"), "chain: the glyph is not in the first input coverage"),
    ("latn", None, "+ss19", text("acd"), "chain: it is"),
    ("latn", None, None, text("f") + [0x200C] + text("i"), "a ZWNJ between the components stops a ligature"),
    ("latn", None, None, text("f") + [0x200D] + text("i"), "a ZWJ between them does not"),
    ("latn", None, "+ss04", text("ac") + [0x200C] + text("d"), "a ZWNJ in a chain's lookahead is skipped"),
    ("latn", None, "+ss04", text("a") + [0x200C] + text("cd"), "a ZWNJ in a chain's backtrack is skipped"),
    ("latn", None, None, text("a") + [0x200D, 0xAD] + text("b"), "default-ignorables are drawn as nothing"),
    ("latn", "TRK ", None, text("fi"), "a language system"),
    (None, None, None, text("fi"), "no script given: DFLT, then dflt, then latn"),
    ("latn", None, "+ss01,+ss03,+ss04", text("abcabcde"), "three features that interact"),
]


def gsub_extras(font):
    """Lookups fontTools' feature compiler will not write, added to the table.

    Context format 1 (glyph rules) and 2 (class rules), chain format 2, and a
    multiple substitution that deletes the glyph. Each is wired to a feature of
    its own so a case can ask for it.
    """
    gsub = font["GSUB"].table
    lookups = gsub.LookupList.Lookup

    def add_lookup(kind, subtable):
        lookup = ot.Lookup()
        lookup.LookupType = kind
        lookup.LookupFlag = 0
        lookup.SubTable = [subtable]
        lookup.SubTableCount = 1
        lookups.append(lookup)
        gsub.LookupList.LookupCount = len(lookups)
        return len(lookups) - 1

    def coverage(names):
        c = ot.Coverage()
        c.glyphs = list(names)
        return c

    def single(mapping):
        s = ot.SingleSubst()
        s.mapping = dict(mapping)
        return s

    def multiple(mapping):
        s = ot.MultipleSubst()
        s.mapping = {k: list(v) for k, v in mapping.items()}
        return s

    def record(sequence, lookup):
        r = ot.SubstLookupRecord()
        r.SequenceIndex = sequence
        r.LookupListIndex = lookup
        return r

    # The nested lookups each act on a glyph the rule that calls it names, so that
    # a case shows *which* rule fired: a lookup that maps a glyph the rule does not
    # reach would pass whether or not the rule was chosen.
    k_to_b = add_lookup(1, single({"k": "b"}))
    l_to_x = add_lookup(1, single({"l": "x"}))
    dup_cd = add_lookup(2, multiple({"c": ["c", "c"], "d": ["d", "d"]}))
    delete_u = add_lookup(2, multiple({"u": []}))

    # Context format 1: "j k l" turns the l into x, and "j k" alone turns the k
    # into b; the longer rule comes first, so rule order decides which fires.
    c1 = ot.ContextSubst()
    c1.Format = 1
    c1.Coverage = coverage(["j"])
    rule_a = ot.SubRule()
    rule_a.Input = ["k", "l"]
    rule_a.GlyphCount = 3
    rule_a.SubstLookupRecord = [record(2, l_to_x)]
    rule_a.SubstCount = 1
    rule_b = ot.SubRule()
    rule_b.Input = ["k"]
    rule_b.GlyphCount = 2
    rule_b.SubstLookupRecord = [record(1, k_to_b)]
    rule_b.SubstCount = 1
    rules = ot.SubRuleSet()
    rules.SubRule = [rule_a, rule_b]
    rules.SubRuleCount = 2
    c1.SubRuleSet = [rules]
    c1.SubRuleSetCount = 1
    ctx1 = add_lookup(5, c1)

    # Context format 2: classes. Class 1 is {a, b}, class 2 is {c, d}; a class-1
    # glyph followed by a class-2 glyph doubles that glyph.
    c2 = ot.ContextSubst()
    c2.Format = 2
    c2.Coverage = coverage(["a", "b"])
    cd = ot.ClassDef()
    cd.classDefs = {"a": 1, "b": 1, "c": 2, "d": 2}
    c2.ClassDef = cd
    rule = ot.SubClassRule()
    rule.Class = [2]
    rule.GlyphCount = 2
    rule.SubstLookupRecord = [record(1, dup_cd)]
    rule.SubstCount = 1
    cset = ot.SubClassSet()
    cset.SubClassRule = [rule]
    cset.SubClassRuleCount = 1
    c2.SubClassSet = [None, cset]
    c2.SubClassSetCount = 2
    ctx2 = add_lookup(5, c2)

    # Chain format 2: with classes on all three sides - s before, "t u" as the
    # input, v after - and the u deleted.
    ch = ot.ChainContextSubst()
    ch.Format = 2
    ch.Coverage = coverage(["t"])
    back = ot.ClassDef()
    back.classDefs = {"s": 1}
    inp = ot.ClassDef()
    inp.classDefs = {"t": 1, "u": 2}
    ahead = ot.ClassDef()
    ahead.classDefs = {"v": 1}
    ch.BacktrackClassDef = back
    ch.InputClassDef = inp
    ch.LookAheadClassDef = ahead
    crule = ot.ChainSubClassRule()
    crule.Backtrack = [1]
    crule.BacktrackGlyphCount = 1
    crule.Input = [2]
    crule.InputGlyphCount = 2
    crule.LookAhead = [1]
    crule.LookAheadGlyphCount = 1
    crule.SubstLookupRecord = [record(1, delete_u)]
    crule.SubstCount = 1
    cs = ot.ChainSubClassSet()
    cs.ChainSubClassRule = [crule]
    cs.ChainSubClassRuleCount = 1
    ch.ChainSubClassSet = [None, cs]
    ch.ChainSubClassSetCount = 2
    chain2 = add_lookup(6, ch)

    # A plain run of lookups used on their own: a multiple to nothing.
    del_only = add_lookup(2, multiple({"e": []}))

    # Nested lookups indexed into the *current* sequence, which is what the
    # specification says a sequence index is: after the first lookup turns "a"
    # into "a a", the "b" that followed it is at index 2 and the "c" at 3. (The
    # feature file's ss03 names the original indices, and so applies its second
    # and third lookups to the wrong glyphs - which is the behaviour the engine
    # has to reproduce, and why both are here.)
    a2 = add_lookup(2, multiple({"a": ["a", "a"]}))
    b2x = add_lookup(1, single({"b": "x"}))
    c3 = add_lookup(2, multiple({"c": ["c", "c", "c"]}))
    c3rec = ot.ContextSubst()
    c3rec.Format = 3
    c3rec.Coverage = [coverage(["a"]), coverage(["b"]), coverage(["c"])]
    c3rec.GlyphCount = 3
    c3rec.SubstLookupRecord = [record(0, a2), record(2, b2x), record(3, c3)]
    c3rec.SubstCount = 3
    shifted = add_lookup(5, c3rec)

    # The same, with the sequence indices of the *original* run, to be clamped
    # when an earlier lookup shrinks it: "d e f" with the middle deleted, then a
    # lookup aimed at what used to be the third glyph.
    del_mid = add_lookup(2, multiple({"e": []}))
    f_to_x = add_lookup(1, single({"f": "x"}))
    shrink = ot.ContextSubst()
    shrink.Format = 3
    shrink.Coverage = [coverage(["d"]), coverage(["e"]), coverage(["f"])]
    shrink.GlyphCount = 3
    shrink.SubstLookupRecord = [record(1, del_mid), record(1, f_to_x)]
    shrink.SubstCount = 2
    shrunk = add_lookup(5, shrink)

    # Wire each to a feature, on the DFLT and latn language systems.
    def add_feature(tag, lookup_indices):
        feature_list = gsub.FeatureList
        record_ = ot.FeatureRecord()
        record_.FeatureTag = tag
        record_.Feature = ot.Feature()
        record_.Feature.FeatureParams = None
        record_.Feature.LookupListIndex = list(lookup_indices)
        record_.Feature.LookupCount = len(lookup_indices)
        feature_list.FeatureRecord.append(record_)
        feature_list.FeatureCount = len(feature_list.FeatureRecord)
        index = len(feature_list.FeatureRecord) - 1
        for script in gsub.ScriptList.ScriptRecord:
            tables = [script.Script.DefaultLangSys] + [
                lr.LangSys for lr in script.Script.LangSysRecord]
            for lang in tables:
                if lang is not None:
                    lang.FeatureIndex.append(index)
                    lang.FeatureCount = len(lang.FeatureIndex)

    # More nested-lookup bookkeeping. Records out of order, so that the second
    # rewinds over what the first left behind (c tripled, then the b, which is now
    # in the middle of the output and not at the cursor, becomes an x); and
    # a record aimed at the glyph an earlier record's multiple substitution just
    # inserted (index 1 after a is doubled).
    a_to_x = add_lookup(1, single({"a": "x"}))
    backwards = ot.ContextSubst()
    backwards.Format = 3
    backwards.Coverage = [coverage(["a"]), coverage(["b"]), coverage(["c"])]
    backwards.GlyphCount = 3
    backwards.SubstLookupRecord = [record(2, c3), record(1, b2x)]
    backwards.SubstCount = 2
    rewinds = add_lookup(5, backwards)
    aimed = ot.ContextSubst()
    aimed.Format = 3
    aimed.Coverage = [coverage(["a"]), coverage(["b"]), coverage(["c"])]
    aimed.GlyphCount = 3
    aimed.SubstLookupRecord = [record(0, a2), record(1, a_to_x)]
    aimed.SubstCount = 2
    inserted = add_lookup(5, aimed)

    # A ligature of one component, which is a plain replacement and not a ligature.
    one = ot.LigatureSubst()
    lig = ot.Ligature()
    lig.LigGlyph = "k"
    lig.Component = []
    lig.CompCount = 1
    one.ligatures = {"j": [lig]}
    single_lig = add_lookup(4, one)

    # A reverse chaining lookup called from a context, which it may not be.
    reverse_index = [i for i, l in enumerate(lookups) if l.LookupType == 8][0]
    call_reverse = ot.ContextSubst()
    call_reverse.Format = 3
    call_reverse.Coverage = [coverage(["p"]), coverage(["q"])]
    call_reverse.GlyphCount = 2
    call_reverse.SubstLookupRecord = [record(0, reverse_index)]
    call_reverse.SubstCount = 1
    called = add_lookup(5, call_reverse)

    add_feature("ss09", [ctx1])
    add_feature("ss10", [ctx2])
    add_feature("ss11", [chain2])
    add_feature("ss12", [del_only])
    add_feature("ss13", [shifted])
    add_feature("ss14", [shrunk])
    add_feature("ss20", [rewinds])
    add_feature("ss21", [inserted])
    add_feature("ss22", [single_lig])
    add_feature("ss23", [called])


GSUB_EXTRA_CASES = [
    ("latn", None, "+ss09", text("jkl"), "context format 1, the longer rule first"),
    ("latn", None, "+ss09", text("jk"), "context format 1, second rule"),
    ("latn", None, "+ss09", text("jx"), "context format 1, no rule"),
    ("latn", None, "+ss10", text("ac"), "context format 2, class rule"),
    ("latn", None, "+ss10", text("bd"), "context format 2, another member"),
    ("latn", None, "+ss10", text("ab"), "context format 2, class with no rule"),
    ("latn", None, "+ss11", text("stuv"), "chain format 2, deleting the glyph"),
    ("latn", None, "+ss11", text("ktuv"), "chain format 2, wrong backtrack"),
    ("latn", None, "+ss11", text("stu"), "chain format 2, no lookahead"),
    ("latn", None, "+ss12", text("aeb"), "multiple substitution to nothing"),
    ("latn", None, "+ss12", text("ee"), "multiple substitution to nothing, twice"),
    ("latn", None, "+ss12", text("e"), "multiple substitution to nothing, all of it"),
    ("latn", None, "+ss12", text("eb"), "multiple substitution to nothing, the first: the cluster goes forward"),
    ("latn", None, "+ss13", text("abc"), "sequence indices follow the run as it grows"),
    ("latn", None, "+ss13", text("abcabc"), "the same twice in a run"),
    ("latn", None, "+ss14", text("def"), "sequence indices follow the run as it shrinks"),
    ("latn", None, "+ss14", text("defdef"), "the same twice in a run"),
    ("latn", None, "+ss13,+ss14", text("abcdef"), "both"),
    ("latn", None, "+ss20", text("abc"), "records out of order: the second rewinds over the first's output"),
    ("latn", None, "+ss20", text("abcabc"), "the same twice in a run"),
    ("latn", None, "+ss21", text("abc"), "a record aimed at the glyph an earlier one inserted"),
    ("latn", None, "+ss22", text("j"), "a ligature of one component"),
    ("latn", None, "+ss23", text("pq"), "a reverse lookup called from a context does nothing"),
    ("latn", None, "+ss24", text("ppqr"), "reverse chaining behind an extension runs backward"),
]


def build_layout_gsub(mf, out):
    fb = build_font(mf, "Layout GSUB", GSUB_GLYPHS, GSUB_ADVANCES, GSUB_CMAP,
                    GSUB_FEA)
    gsub_extras(fb.font)
    fb.save(out)


def build_layout_gsub_cases(mf, out):
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(cases_text(GSUB_CASES + GSUB_EXTRA_CASES))


# --- GPOS ----------------------------------------------------------------

GPOS_GLYPHS = ["A", "V", "T", "a", "o", "x", "y", "f", "i", "f_i", "c1", "c2",
               "c3", "acute", "grave", "dotbelow"]

GPOS_ADVANCES = {"A": 700, "V": 700, "T": 600, "a": 500, "o": 520, "x": 480,
                 "y": 480, "f": 330, "i": 260, "f_i": 560, "c1": 600,
                 "c2": 600, "c3": 600, "acute": 0, "grave": 0, "dotbelow": 0}

GPOS_CMAP = {0x41: "A", 0x56: "V", 0x54: "T", 0x61: "a", 0x6F: "o", 0x78: "x",
             0x79: "y", 0x66: "f", 0x69: "i", 0x63: "c1", 0x64: "c2",
             0x65: "c3", 0x301: "acute", 0x300: "grave", 0x323: "dotbelow"}

GPOS_FEA = """
languagesystem DFLT dflt;
languagesystem latn dflt;

@BASES = [A V T a o x y f i c1 c2 c3];
@MARKS = [acute grave dotbelow];

table GDEF {
    GlyphClassDef @BASES, [f_i], @MARKS, ;
} GDEF;

# The ligature the mark-to-ligature lookup attaches to. IgnoreMarks, so that a
# mark between the f and the i does not stop it and becomes its first component's.
feature liga { lookupflag IgnoreMarks; sub f i by f_i; } liga;

# Pair adjustment. Format 1 is the glyph pairs, with a value for each glyph in one
# of them; format 2 is the class pairs.
@C1 = [a o];
@C2 = [x y];
feature kern {
    pos A V -80;
    pos T o <-30 0 -60 0>;
    pos A <10 0 -50 0> T <0 5 5 0>;
    pos [a] [y] -10;
    pos @C1 @C2 -40;
    pos [A V] [a o] <0 0 -20 0>;
    # One first glyph with five partners, so a pair set is searched and not just read.
    pos f x -11;
    pos f y -12;
    pos f a -13;
    pos f o -14;
    pos f T -15;
} kern;

# A lookup that says the line runs right to left, defined first so that it runs
# before the left-to-right one below when both are on: the second then re-parents
# glyphs the first attached, which is the one thing reversing a chain is for.
lookup CURS_RTL {
    lookupflag RightToLeft;
    pos cursive c1 <anchor NULL> <anchor 100 20>;
    pos cursive c2 <anchor 0 -10> <anchor 120 10>;
    pos cursive c3 <anchor -20 0> <anchor NULL>;
} CURS_RTL;
# Cursive attachment: three glyphs that connect, with entry and exit anchors.
feature curs {
    pos cursive c1 <anchor NULL> <anchor 100 20>;
    pos cursive c2 <anchor 0 -10> <anchor 120 10>;
    pos cursive c3 <anchor -20 0> <anchor NULL>;
} curs;

feature ss06 { lookup CURS_RTL; } ss06;

# Mark to base, to ligature (a mark on each component) and to mark.
markClass acute <anchor 0 650> @TOP;
markClass grave <anchor 0 650> @TOP;
markClass dotbelow <anchor 50 0> @BOTTOM;
markClass grave <anchor 0 0> @ONMARK;
feature mark {
    pos base [a o x] <anchor 250 520> mark @TOP;
    pos base A <anchor 320 720> mark @TOP;
    pos base [a o] <anchor 250 -10> mark @BOTTOM;
    pos ligature f_i <anchor 200 700> mark @TOP
        ligComponent <anchor 450 700> mark @TOP;
} mark;
feature mkmk { pos mark acute <anchor 0 140> mark @ONMARK; } mkmk;

# Single adjustment: one value for the set, and a value for each glyph.
feature ss01 { pos a <10 20 30 40>; } ss01;
feature ss02 {
    pos A <0 0 -10 0>;
    pos V <5 0 20 0>;
} ss02;
# A value with device tables, which a font at its own size does not use.
feature ss07 { pos x <0 0 0 0 <device 11 1, 12 2> <device NULL> <device NULL> <device NULL>>; } ss07;

# Contextual adjustment: a chain, and a context applying two nested lookups.
lookup P_GEN { pos [A V a o] <0 0 -50 0>; } P_GEN;
feature ss03 { pos a' lookup P_GEN o; } ss03;
feature ss04 { pos A' lookup P_GEN V' lookup P_GEN; } ss04;

# A lookup behind an extension subtable.
lookup K_EXT useExtension { pos A T -25; } K_EXT;
feature ss05 { lookup K_EXT; } ss05;

# Mark to mark in a lookup that skips ligatures: a mark that follows a ligature
# glyph must still be looked for before it, and the ligature is not a mark.
feature ss08 { lookupflag IgnoreLigatures; pos mark acute <anchor 0 140> mark @ONMARK; } ss08;
"""

GPOS_CASES = [
    ("latn", None, None, text("AV"), "pair, format 1"),
    ("latn", None, None, text("To"), "pair with a value record for the first glyph"),
    ("latn", None, None, text("AT"), "pair with a value for each glyph"),
    ("latn", None, None, text("TA"), "a pair that is not in the table"),
    ("latn", None, None, text("ay"), "pair, format 1 beside classes"),
    ("latn", None, None, text("ox"), "pair, format 2"),
    ("latn", None, None, text("ay"), "pair, format 2"),
    ("latn", None, None, text("Aa"), "pair, format 2 second subtable"),
    ("latn", None, None, text("VoAy"), "pairs in a run"),
    ("latn", None, "-kern", text("AVAT"), "kerning off"),
    ("latn", None, "kern[1:3]", text("AVAV"), "kerning over a range"),
    ("latn", None, None, text("cde"), "cursive attachment"),
    ("latn", None, None, text("cc"), "cursive: exit to entry-less glyph"),
    ("latn", None, None, text("ecd"), "cursive: entry-only first"),
    ("latn", None, None, text("cdecde"), "cursive in a run"),
    ("latn", None, "+ss06", text("cde"), "cursive, right-to-left flag"),
    ("latn", None, "+ss06", text("dd"), "cursive, right-to-left flag, twice"),
    ("latn", None, None, text("a") + [0x301], "mark to base"),
    ("latn", None, None, text("A") + [0x301], "mark to another base"),
    ("latn", None, None, text("x") + [0x301, 0x300], "two marks on one base"),
    ("latn", None, None, text("o") + [0x323], "mark below"),
    ("latn", None, None, text("a") + [0x323, 0x301], "marks above and below, in canonical order"),
    ("latn", None, None, text("f") + [0x301] + text("i"), "mark on a ligature's first component"),
    ("latn", None, None, text("fi") + [0x301], "mark on a ligature's last component"),
    ("latn", None, None, text("a") + [0x301, 0x300], "mark to mark"),
    ("latn", None, None, text("a") + [0x300, 0x301], "mark to mark, the other way"),
    ("latn", None, None, text("aa") + [0x301] + text("a"), "marks and bases in a run"),
    ("latn", None, "-mark", text("a") + [0x301], "mark positioning off"),
    ("latn", None, "+ss01", text("aa"), "single adjustment, format 1"),
    ("latn", None, "+ss02", text("AV"), "single adjustment, format 2"),
    ("latn", None, "+ss02", text("T"), "single adjustment, glyph not covered"),
    ("latn", None, "+ss07", text("xx"), "a value with device tables"),
    ("latn", None, "+ss03", text("ao"), "contextual adjustment, a chain"),
    ("latn", None, "+ss03", text("aa"), "contextual adjustment that does not match"),
    ("latn", None, "+ss04", text("AV"), "contextual adjustment, two nested lookups"),
    ("latn", None, "+ss05", text("AT"), "a lookup behind an extension"),
    ("latn", None, "+ss01,+ss02,+ss05", text("AVAT"), "adjustments that add"),
    ("latn", None, None, text("fT"), "a pair set of five: the last"),
    ("latn", None, None, text("fa"), "a pair set of five: the middle"),
    ("latn", None, None, text("fo"), "a pair set of five: another"),
    ("latn", None, None, text("fx"), "a pair set of five: the first"),
    ("latn", None, None, text("fy"), "a pair set of five: another"),
    ("latn", None, None, text("fA"), "a pair set of five: not in it"),
    ("latn", None, None, text("ATo"), "a pair with a value for the second glyph skips it for the next pair"),
    ("latn", None, "kern[1:2]=0", text("AV"), "the second glyph has the feature off: no pair"),
    ("latn", None, None, text("f") + [0x301] + text("i") + [0x300],
        "marks on a ligature's two components: the second is not on the first"),
    ("latn", None, None, (text("f") + [0x301] + text("i")) * 9,
        "nine ligatures, so a ligature id is reused and marks still find their component"),
    ("latn", None, "+ss08", [0x301] + text("fi") + [0x300], "mark to mark that skips ligatures"),
]


def gpos_extras(font):
    """GPOS contexts the feature compiler will not write: formats 1 and 2, and
    a chain in format 2, each wired to a feature of its own."""
    gpos = font["GPOS"].table
    lookups = gpos.LookupList.Lookup

    def add_lookup(kind, subtable):
        lookup = ot.Lookup()
        lookup.LookupType = kind
        lookup.LookupFlag = 0
        lookup.SubTable = [subtable]
        lookup.SubTableCount = 1
        lookups.append(lookup)
        gpos.LookupList.LookupCount = len(lookups)
        return len(lookups) - 1

    def coverage(names):
        c = ot.Coverage()
        c.glyphs = list(names)
        return c

    def value(x_advance):
        v = ot.ValueRecord()
        v.XAdvance = x_advance
        return v

    def single_pos(glyphs, x_advance):
        s = ot.SinglePos()
        s.Format = 1
        s.Coverage = coverage(glyphs)
        s.ValueFormat = 4
        s.Value = value(x_advance)
        return s

    def record(sequence, lookup):
        r = ot.PosLookupRecord()
        r.SequenceIndex = sequence
        r.LookupListIndex = lookup
        return r

    tighten = add_lookup(1, single_pos(["A", "V", "T", "a", "o"], -35))
    loosen = add_lookup(1, single_pos(["A", "V", "T", "a", "o"], 25))

    # Context format 1: after "T", an "a" is tightened; "T a o" as a whole is
    # a longer rule that comes first, so rule order matters.
    c1 = ot.ContextPos()
    c1.Format = 1
    c1.Coverage = coverage(["T"])
    long_rule = ot.PosRule()
    long_rule.Input = ["a", "o"]
    long_rule.GlyphCount = 3
    long_rule.PosLookupRecord = [record(2, loosen)]
    long_rule.PosCount = 1
    short_rule = ot.PosRule()
    short_rule.Input = ["a"]
    short_rule.GlyphCount = 2
    short_rule.PosLookupRecord = [record(1, tighten)]
    short_rule.PosCount = 1
    rules = ot.PosRuleSet()
    rules.PosRule = [long_rule, short_rule]
    rules.PosRuleCount = 2
    c1.PosRuleSet = [rules]
    c1.PosRuleSetCount = 1
    ctx1 = add_lookup(7, c1)

    # Context format 2: classes. {A V} then {a o}: the second is loosened.
    c2 = ot.ContextPos()
    c2.Format = 2
    c2.Coverage = coverage(["A", "V"])
    cd = ot.ClassDef()
    cd.classDefs = {"A": 1, "V": 1, "a": 2, "o": 2}
    c2.ClassDef = cd
    crule = ot.PosClassRule()
    crule.Class = [2]
    crule.GlyphCount = 2
    crule.PosLookupRecord = [record(1, loosen)]
    crule.PosCount = 1
    cset = ot.PosClassSet()
    cset.PosClassRule = [crule]
    cset.PosClassRuleCount = 1
    c2.PosClassSet = [None, cset]
    c2.PosClassSetCount = 2
    ctx2 = add_lookup(7, c2)

    # Chain format 2.
    ch = ot.ChainContextPos()
    ch.Format = 2
    ch.Coverage = coverage(["a"])
    back = ot.ClassDef()
    back.classDefs = {"T": 1}
    inp = ot.ClassDef()
    inp.classDefs = {"a": 1}
    ahead = ot.ClassDef()
    ahead.classDefs = {"o": 1}
    ch.BacktrackClassDef = back
    ch.InputClassDef = inp
    ch.LookAheadClassDef = ahead
    rule = ot.ChainPosClassRule()
    rule.Backtrack = [1]
    rule.BacktrackGlyphCount = 1
    rule.Input = []
    rule.InputGlyphCount = 1
    rule.LookAhead = [1]
    rule.LookAheadGlyphCount = 1
    rule.PosLookupRecord = [record(0, tighten)]
    rule.PosCount = 1
    cs = ot.ChainPosClassSet()
    cs.ChainPosClassRule = [rule]
    cs.ChainPosClassRuleCount = 1
    ch.ChainPosClassSet = [None, cs]
    ch.ChainPosClassSetCount = 2
    chain2 = add_lookup(8, ch)

    def add_feature(tag, lookup_indices):
        feature_list = gpos.FeatureList
        record_ = ot.FeatureRecord()
        record_.FeatureTag = tag
        record_.Feature = ot.Feature()
        record_.Feature.FeatureParams = None
        record_.Feature.LookupListIndex = list(lookup_indices)
        record_.Feature.LookupCount = len(lookup_indices)
        feature_list.FeatureRecord.append(record_)
        feature_list.FeatureCount = len(feature_list.FeatureRecord)
        index = len(feature_list.FeatureRecord) - 1
        for script in gpos.ScriptList.ScriptRecord:
            tables = [script.Script.DefaultLangSys] + [
                lr.LangSys for lr in script.Script.LangSysRecord]
            for lang in tables:
                if lang is not None:
                    lang.FeatureIndex.append(index)
                    lang.FeatureCount = len(lang.FeatureIndex)

    add_feature("ss09", [ctx1])
    add_feature("ss10", [ctx2])
    add_feature("ss11", [chain2])


GPOS_EXTRA_CASES = [
    ("latn", None, "+ss09", text("Tao"), "context format 1, the longer rule first"),
    ("latn", None, "+ss09", text("Ta"), "context format 1, the shorter rule"),
    ("latn", None, "+ss09", text("Tx"), "context format 1, no rule"),
    ("latn", None, "+ss10", text("Aa"), "context format 2"),
    ("latn", None, "+ss10", text("Vo"), "context format 2, another pair"),
    ("latn", None, "+ss10", text("Ax"), "context format 2, class with no rule"),
    ("latn", None, "+ss11", text("Tao"), "chain format 2"),
    ("latn", None, "+ss11", text("ao"), "chain format 2, no backtrack"),
]


def build_layout_gpos(mf, out):
    fb = build_font(mf, "Layout GPOS", GPOS_GLYPHS, GPOS_ADVANCES, GPOS_CMAP,
                    GPOS_FEA)
    gpos_extras(fb.font)
    fb.save(out)


def build_layout_gpos_cases(mf, out):
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(cases_text(GPOS_CASES + GPOS_EXTRA_CASES))


# --- FeatureVariations ---------------------------------------------------

# variable-gvar.ttf's font, with its GSUB 1.1: at wght >= 0.5 (normalised) a bar
# becomes a dot; at wght <= -0.5 and wdth >= 0.25 a tri becomes a ring; at
# wdth <= -0.5 a bar becomes acc and a tri acc2. Where two rules overlap fontTools
# writes a record of its own that overlays them in order, the later winning.
# 'A' is the tri and 'B' the bar; the cases move the location across all four.
VARIATIONS_CASES = [
    (None, None, None, text("AB"), "the default instance: no record holds", ""),
    (None, None, None, text("AB"), "the upper half of weight: bar -> dot", "wght=900"),
    (None, None, None, text("AB"), "light and wide: tri -> ring", "wght=100,wdth=125"),
    (None, None, None, text("AB"), "narrow: bar -> acc and tri -> acc2", "wdth=75"),
    (None, None, None, text("AB"), "heavy and narrow: the overlap has a record of its own, later rule winning",
        "wght=900,wdth=75"),
    (None, None, None, text("AB"), "just short of the weight condition (avar bends 560 to 0.48)", "wght=560"),
    (None, None, None, text("AB"), "just past it (575 is 0.525)", "wght=575"),
    (None, None, None, text("BAB"), "a run", "wght=900"),
]


def build_variable_featurevars_cases(mf, out):
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(cases_text(VARIATIONS_CASES))
