/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Font.
 *
 * Ghoti.io Font is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Font is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/* Generated by tools/gen/script_tags.py from unicode's enums.h. Do not edit. */

#ifndef GHOTI_IO_GFNT_SCRIPT_TAGS_H
#define GHOTI_IO_GFNT_SCRIPT_TAGS_H

#include <ghoti.io/font/macros.h>

static const char gfnt_script_tags[176][5] = {
  "", /* 0 */
  "adlm", /* 1 */
  "ahom", /* 2 */
  "hluw", /* 3 */
  "arab", /* 4 */
  "armn", /* 5 */
  "avst", /* 6 */
  "bali", /* 7 */
  "bamu", /* 8 */
  "bass", /* 9 */
  "batk", /* 10 */
  "beng", /* 11 */
  "berf", /* 12 */
  "bhks", /* 13 */
  "bopo", /* 14 */
  "brah", /* 15 */
  "brai", /* 16 */
  "bugi", /* 17 */
  "buhd", /* 18 */
  "cans", /* 19 */
  "cari", /* 20 */
  "aghb", /* 21 */
  "cakm", /* 22 */
  "cham", /* 23 */
  "cher", /* 24 */
  "chrs", /* 25 */
  "", /* 26 */
  "copt", /* 27 */
  "xsux", /* 28 */
  "cprt", /* 29 */
  "cpmn", /* 30 */
  "cyrl", /* 31 */
  "dsrt", /* 32 */
  "deva", /* 33 */
  "diak", /* 34 */
  "dogr", /* 35 */
  "dupl", /* 36 */
  "egyp", /* 37 */
  "elba", /* 38 */
  "elym", /* 39 */
  "ethi", /* 40 */
  "gara", /* 41 */
  "geor", /* 42 */
  "glag", /* 43 */
  "goth", /* 44 */
  "gran", /* 45 */
  "grek", /* 46 */
  "gujr", /* 47 */
  "gong", /* 48 */
  "guru", /* 49 */
  "gukh", /* 50 */
  "hani", /* 51 */
  "hang", /* 52 */
  "rohg", /* 53 */
  "hano", /* 54 */
  "hatr", /* 55 */
  "hebr", /* 56 */
  "kana", /* 57 */
  "armi", /* 58 */
  "", /* 59 */
  "phli", /* 60 */
  "prti", /* 61 */
  "java", /* 62 */
  "kthi", /* 63 */
  "knda", /* 64 */
  "kana", /* 65 */
  "kana", /* 66 */
  "kawi", /* 67 */
  "kali", /* 68 */
  "khar", /* 69 */
  "kits", /* 70 */
  "khmr", /* 71 */
  "khoj", /* 72 */
  "sind", /* 73 */
  "krai", /* 74 */
  "laoo", /* 75 */
  "latn", /* 76 */
  "lepc", /* 77 */
  "limb", /* 78 */
  "lina", /* 79 */
  "linb", /* 80 */
  "lisu", /* 81 */
  "lyci", /* 82 */
  "lydi", /* 83 */
  "mahj", /* 84 */
  "maka", /* 85 */
  "mlym", /* 86 */
  "mand", /* 87 */
  "mani", /* 88 */
  "marc", /* 89 */
  "gonm", /* 90 */
  "medf", /* 91 */
  "mtei", /* 92 */
  "mend", /* 93 */
  "merc", /* 94 */
  "mero", /* 95 */
  "miao", /* 96 */
  "modi", /* 97 */
  "mong", /* 98 */
  "mroo", /* 99 */
  "mult", /* 100 */
  "mymr", /* 101 */
  "nbat", /* 102 */
  "nagm", /* 103 */
  "nand", /* 104 */
  "talu", /* 105 */
  "newa", /* 106 */
  "nko ", /* 107 */
  "nshu", /* 108 */
  "hmnp", /* 109 */
  "ogam", /* 110 */
  "olck", /* 111 */
  "onao", /* 112 */
  "hung", /* 113 */
  "ital", /* 114 */
  "narb", /* 115 */
  "perm", /* 116 */
  "xpeo", /* 117 */
  "sogo", /* 118 */
  "sarb", /* 119 */
  "orkh", /* 120 */
  "ougr", /* 121 */
  "orya", /* 122 */
  "osge", /* 123 */
  "osma", /* 124 */
  "hmng", /* 125 */
  "palm", /* 126 */
  "pauc", /* 127 */
  "phag", /* 128 */
  "phnx", /* 129 */
  "phlp", /* 130 */
  "rjng", /* 131 */
  "runr", /* 132 */
  "samr", /* 133 */
  "saur", /* 134 */
  "shrd", /* 135 */
  "shaw", /* 136 */
  "sidd", /* 137 */
  "sidt", /* 138 */
  "sgnw", /* 139 */
  "sinh", /* 140 */
  "sogd", /* 141 */
  "sora", /* 142 */
  "soyo", /* 143 */
  "sund", /* 144 */
  "sunu", /* 145 */
  "sylo", /* 146 */
  "syrc", /* 147 */
  "tglg", /* 148 */
  "tagb", /* 149 */
  "tale", /* 150 */
  "lana", /* 151 */
  "tavt", /* 152 */
  "tayo", /* 153 */
  "takr", /* 154 */
  "taml", /* 155 */
  "tnsa", /* 156 */
  "tang", /* 157 */
  "telu", /* 158 */
  "thaa", /* 159 */
  "thai", /* 160 */
  "tibt", /* 161 */
  "tfng", /* 162 */
  "tirh", /* 163 */
  "todr", /* 164 */
  "tols", /* 165 */
  "toto", /* 166 */
  "tutg", /* 167 */
  "ugar", /* 168 */
  "vaii", /* 169 */
  "vith", /* 170 */
  "wcho", /* 171 */
  "wara", /* 172 */
  "yezi", /* 173 */
  "yiii", /* 174 */
  "zanb", /* 175 */
};
#define GFNT_SCRIPT_TAG_COUNT 176

#endif
