/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Font.
 *
 * Ghoti.io Font is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Font is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * **Generated by tools/vectors/make_vectors.py. Do not edit.**
 *
 * The CFF standard strings, the Standard Encoding, and the two
 * predefined charsets. From fontTools' `cffStandardStrings`,
 * `StandardEncoding`, `cffIExpertStrings` and
 * `cffExpertSubsetStrings`. design.md section 7.4.
 *
 * Regenerate with `make gen-vectors`, which runs that script in the pinned
 * `fonttools` image; `make check-vectors` fails when this file is not what it
 * emits. documentation/design.md sections 7.2 and 14.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#ifndef GHOTI_IO_GFNT_CFF_STRINGS_H
#define GHOTI_IO_GFNT_CFF_STRINGS_H

// Before anything is declared, so that namespace.h's renames are already in
// effect - CONVENTIONS.md section 4, enforced by check-symbols.
#include <ghoti.io/font/macros.h>
#include <stdint.h>

/** @brief How many standard strings CFF predefines. */
#define GFNT_CFF_STANDARD_STRING_COUNT 391

/**
 * @brief How many glyphs the ISOAdobe charset names.
 *
 * Predefined charset 0, which is also what a font with no `charset` entry at
 * all uses: glyph *i* is SID *i*, and a font with more glyphs than this names
 * the rest not at all.
 */
#define GFNT_CFF_ISO_ADOBE_COUNT 229

/**
 * @brief The standard strings, indexed by SID.
 *
 * A `charset` gives each glyph a SID. One below
 * ::GFNT_CFF_STANDARD_STRING_COUNT names one of these; one at or above it
 * indexes the `String` INDEX of the font itself, offset by this count.
 */
static const char * const gfnt_cff_standard_strings[
    GFNT_CFF_STANDARD_STRING_COUNT] = {
  ".notdef", // 0
  "space", // 1
  "exclam", // 2
  "quotedbl", // 3
  "numbersign", // 4
  "dollar", // 5
  "percent", // 6
  "ampersand", // 7
  "quoteright", // 8
  "parenleft", // 9
  "parenright", // 10
  "asterisk", // 11
  "plus", // 12
  "comma", // 13
  "hyphen", // 14
  "period", // 15
  "slash", // 16
  "zero", // 17
  "one", // 18
  "two", // 19
  "three", // 20
  "four", // 21
  "five", // 22
  "six", // 23
  "seven", // 24
  "eight", // 25
  "nine", // 26
  "colon", // 27
  "semicolon", // 28
  "less", // 29
  "equal", // 30
  "greater", // 31
  "question", // 32
  "at", // 33
  "A", // 34
  "B", // 35
  "C", // 36
  "D", // 37
  "E", // 38
  "F", // 39
  "G", // 40
  "H", // 41
  "I", // 42
  "J", // 43
  "K", // 44
  "L", // 45
  "M", // 46
  "N", // 47
  "O", // 48
  "P", // 49
  "Q", // 50
  "R", // 51
  "S", // 52
  "T", // 53
  "U", // 54
  "V", // 55
  "W", // 56
  "X", // 57
  "Y", // 58
  "Z", // 59
  "bracketleft", // 60
  "backslash", // 61
  "bracketright", // 62
  "asciicircum", // 63
  "underscore", // 64
  "quoteleft", // 65
  "a", // 66
  "b", // 67
  "c", // 68
  "d", // 69
  "e", // 70
  "f", // 71
  "g", // 72
  "h", // 73
  "i", // 74
  "j", // 75
  "k", // 76
  "l", // 77
  "m", // 78
  "n", // 79
  "o", // 80
  "p", // 81
  "q", // 82
  "r", // 83
  "s", // 84
  "t", // 85
  "u", // 86
  "v", // 87
  "w", // 88
  "x", // 89
  "y", // 90
  "z", // 91
  "braceleft", // 92
  "bar", // 93
  "braceright", // 94
  "asciitilde", // 95
  "exclamdown", // 96
  "cent", // 97
  "sterling", // 98
  "fraction", // 99
  "yen", // 100
  "florin", // 101
  "section", // 102
  "currency", // 103
  "quotesingle", // 104
  "quotedblleft", // 105
  "guillemotleft", // 106
  "guilsinglleft", // 107
  "guilsinglright", // 108
  "fi", // 109
  "fl", // 110
  "endash", // 111
  "dagger", // 112
  "daggerdbl", // 113
  "periodcentered", // 114
  "paragraph", // 115
  "bullet", // 116
  "quotesinglbase", // 117
  "quotedblbase", // 118
  "quotedblright", // 119
  "guillemotright", // 120
  "ellipsis", // 121
  "perthousand", // 122
  "questiondown", // 123
  "grave", // 124
  "acute", // 125
  "circumflex", // 126
  "tilde", // 127
  "macron", // 128
  "breve", // 129
  "dotaccent", // 130
  "dieresis", // 131
  "ring", // 132
  "cedilla", // 133
  "hungarumlaut", // 134
  "ogonek", // 135
  "caron", // 136
  "emdash", // 137
  "AE", // 138
  "ordfeminine", // 139
  "Lslash", // 140
  "Oslash", // 141
  "OE", // 142
  "ordmasculine", // 143
  "ae", // 144
  "dotlessi", // 145
  "lslash", // 146
  "oslash", // 147
  "oe", // 148
  "germandbls", // 149
  "onesuperior", // 150
  "logicalnot", // 151
  "mu", // 152
  "trademark", // 153
  "Eth", // 154
  "onehalf", // 155
  "plusminus", // 156
  "Thorn", // 157
  "onequarter", // 158
  "divide", // 159
  "brokenbar", // 160
  "degree", // 161
  "thorn", // 162
  "threequarters", // 163
  "twosuperior", // 164
  "registered", // 165
  "minus", // 166
  "eth", // 167
  "multiply", // 168
  "threesuperior", // 169
  "copyright", // 170
  "Aacute", // 171
  "Acircumflex", // 172
  "Adieresis", // 173
  "Agrave", // 174
  "Aring", // 175
  "Atilde", // 176
  "Ccedilla", // 177
  "Eacute", // 178
  "Ecircumflex", // 179
  "Edieresis", // 180
  "Egrave", // 181
  "Iacute", // 182
  "Icircumflex", // 183
  "Idieresis", // 184
  "Igrave", // 185
  "Ntilde", // 186
  "Oacute", // 187
  "Ocircumflex", // 188
  "Odieresis", // 189
  "Ograve", // 190
  "Otilde", // 191
  "Scaron", // 192
  "Uacute", // 193
  "Ucircumflex", // 194
  "Udieresis", // 195
  "Ugrave", // 196
  "Yacute", // 197
  "Ydieresis", // 198
  "Zcaron", // 199
  "aacute", // 200
  "acircumflex", // 201
  "adieresis", // 202
  "agrave", // 203
  "aring", // 204
  "atilde", // 205
  "ccedilla", // 206
  "eacute", // 207
  "ecircumflex", // 208
  "edieresis", // 209
  "egrave", // 210
  "iacute", // 211
  "icircumflex", // 212
  "idieresis", // 213
  "igrave", // 214
  "ntilde", // 215
  "oacute", // 216
  "ocircumflex", // 217
  "odieresis", // 218
  "ograve", // 219
  "otilde", // 220
  "scaron", // 221
  "uacute", // 222
  "ucircumflex", // 223
  "udieresis", // 224
  "ugrave", // 225
  "yacute", // 226
  "ydieresis", // 227
  "zcaron", // 228
  "exclamsmall", // 229
  "Hungarumlautsmall", // 230
  "dollaroldstyle", // 231
  "dollarsuperior", // 232
  "ampersandsmall", // 233
  "Acutesmall", // 234
  "parenleftsuperior", // 235
  "parenrightsuperior", // 236
  "twodotenleader", // 237
  "onedotenleader", // 238
  "zerooldstyle", // 239
  "oneoldstyle", // 240
  "twooldstyle", // 241
  "threeoldstyle", // 242
  "fouroldstyle", // 243
  "fiveoldstyle", // 244
  "sixoldstyle", // 245
  "sevenoldstyle", // 246
  "eightoldstyle", // 247
  "nineoldstyle", // 248
  "commasuperior", // 249
  "threequartersemdash", // 250
  "periodsuperior", // 251
  "questionsmall", // 252
  "asuperior", // 253
  "bsuperior", // 254
  "centsuperior", // 255
  "dsuperior", // 256
  "esuperior", // 257
  "isuperior", // 258
  "lsuperior", // 259
  "msuperior", // 260
  "nsuperior", // 261
  "osuperior", // 262
  "rsuperior", // 263
  "ssuperior", // 264
  "tsuperior", // 265
  "ff", // 266
  "ffi", // 267
  "ffl", // 268
  "parenleftinferior", // 269
  "parenrightinferior", // 270
  "Circumflexsmall", // 271
  "hyphensuperior", // 272
  "Gravesmall", // 273
  "Asmall", // 274
  "Bsmall", // 275
  "Csmall", // 276
  "Dsmall", // 277
  "Esmall", // 278
  "Fsmall", // 279
  "Gsmall", // 280
  "Hsmall", // 281
  "Ismall", // 282
  "Jsmall", // 283
  "Ksmall", // 284
  "Lsmall", // 285
  "Msmall", // 286
  "Nsmall", // 287
  "Osmall", // 288
  "Psmall", // 289
  "Qsmall", // 290
  "Rsmall", // 291
  "Ssmall", // 292
  "Tsmall", // 293
  "Usmall", // 294
  "Vsmall", // 295
  "Wsmall", // 296
  "Xsmall", // 297
  "Ysmall", // 298
  "Zsmall", // 299
  "colonmonetary", // 300
  "onefitted", // 301
  "rupiah", // 302
  "Tildesmall", // 303
  "exclamdownsmall", // 304
  "centoldstyle", // 305
  "Lslashsmall", // 306
  "Scaronsmall", // 307
  "Zcaronsmall", // 308
  "Dieresissmall", // 309
  "Brevesmall", // 310
  "Caronsmall", // 311
  "Dotaccentsmall", // 312
  "Macronsmall", // 313
  "figuredash", // 314
  "hypheninferior", // 315
  "Ogoneksmall", // 316
  "Ringsmall", // 317
  "Cedillasmall", // 318
  "questiondownsmall", // 319
  "oneeighth", // 320
  "threeeighths", // 321
  "fiveeighths", // 322
  "seveneighths", // 323
  "onethird", // 324
  "twothirds", // 325
  "zerosuperior", // 326
  "foursuperior", // 327
  "fivesuperior", // 328
  "sixsuperior", // 329
  "sevensuperior", // 330
  "eightsuperior", // 331
  "ninesuperior", // 332
  "zeroinferior", // 333
  "oneinferior", // 334
  "twoinferior", // 335
  "threeinferior", // 336
  "fourinferior", // 337
  "fiveinferior", // 338
  "sixinferior", // 339
  "seveninferior", // 340
  "eightinferior", // 341
  "nineinferior", // 342
  "centinferior", // 343
  "dollarinferior", // 344
  "periodinferior", // 345
  "commainferior", // 346
  "Agravesmall", // 347
  "Aacutesmall", // 348
  "Acircumflexsmall", // 349
  "Atildesmall", // 350
  "Adieresissmall", // 351
  "Aringsmall", // 352
  "AEsmall", // 353
  "Ccedillasmall", // 354
  "Egravesmall", // 355
  "Eacutesmall", // 356
  "Ecircumflexsmall", // 357
  "Edieresissmall", // 358
  "Igravesmall", // 359
  "Iacutesmall", // 360
  "Icircumflexsmall", // 361
  "Idieresissmall", // 362
  "Ethsmall", // 363
  "Ntildesmall", // 364
  "Ogravesmall", // 365
  "Oacutesmall", // 366
  "Ocircumflexsmall", // 367
  "Otildesmall", // 368
  "Odieresissmall", // 369
  "OEsmall", // 370
  "Oslashsmall", // 371
  "Ugravesmall", // 372
  "Uacutesmall", // 373
  "Ucircumflexsmall", // 374
  "Udieresissmall", // 375
  "Yacutesmall", // 376
  "Thornsmall", // 377
  "Ydieresissmall", // 378
  "001.000", // 379
  "001.001", // 380
  "001.002", // 381
  "001.003", // 382
  "Black", // 383
  "Bold", // 384
  "Book", // 385
  "Light", // 386
  "Medium", // 387
  "Regular", // 388
  "Roman", // 389
  "Semibold", // 390
};

/**
 * @brief The Standard Encoding, as a SID per code, 0 where nothing is encoded.
 *
 * `seac` - and `endchar` with four or five arguments, which is the same
 * construction - names its accent and its base by **Standard Encoding code**,
 * whatever the font's own encoding is. This table is the only way to read one,
 * and a reader that used the font's encoding instead would place the accent of
 * a re-encoded font on the wrong letter while reporting success.
 */
static const uint16_t gfnt_cff_standard_encoding[256] = {
    0,   0,   0,   0,   0,   0,   0,   0, // 0-7
    0,   0,   0,   0,   0,   0,   0,   0, // 8-15
    0,   0,   0,   0,   0,   0,   0,   0, // 16-23
    0,   0,   0,   0,   0,   0,   0,   0, // 24-31
    1,   2,   3,   4,   5,   6,   7,   8, // 32-39
    9,  10,  11,  12,  13,  14,  15,  16, // 40-47
   17,  18,  19,  20,  21,  22,  23,  24, // 48-55
   25,  26,  27,  28,  29,  30,  31,  32, // 56-63
   33,  34,  35,  36,  37,  38,  39,  40, // 64-71
   41,  42,  43,  44,  45,  46,  47,  48, // 72-79
   49,  50,  51,  52,  53,  54,  55,  56, // 80-87
   57,  58,  59,  60,  61,  62,  63,  64, // 88-95
   65,  66,  67,  68,  69,  70,  71,  72, // 96-103
   73,  74,  75,  76,  77,  78,  79,  80, // 104-111
   81,  82,  83,  84,  85,  86,  87,  88, // 112-119
   89,  90,  91,  92,  93,  94,  95,   0, // 120-127
    0,   0,   0,   0,   0,   0,   0,   0, // 128-135
    0,   0,   0,   0,   0,   0,   0,   0, // 136-143
    0,   0,   0,   0,   0,   0,   0,   0, // 144-151
    0,   0,   0,   0,   0,   0,   0,   0, // 152-159
    0,  96,  97,  98,  99, 100, 101, 102, // 160-167
  103, 104, 105, 106, 107, 108, 109, 110, // 168-175
    0, 111, 112, 113, 114,   0, 115, 116, // 176-183
  117, 118, 119, 120, 121, 122,   0, 123, // 184-191
    0, 124, 125, 126, 127, 128, 129, 130, // 192-199
  131,   0, 132, 133,   0, 134, 135, 136, // 200-207
  137,   0,   0,   0,   0,   0,   0,   0, // 208-215
    0,   0,   0,   0,   0,   0,   0,   0, // 216-223
    0, 138,   0, 139,   0,   0,   0,   0, // 224-231
  140, 141, 142, 143,   0,   0,   0,   0, // 232-239
    0, 144,   0,   0,   0, 145,   0,   0, // 240-247
  146, 147, 148, 149,   0,   0,   0,   0, // 248-255
};

/** @brief How many glyphs the expert charset names. */
#define GFNT_CFF_EXPERT_CHARSET_COUNT 166

/**
 * @brief Predefined charset 1: the Expert charset, as a SID per glyph.
 *
 * A `charset` offset of 1 **is** this table rather than pointing at one, so a
 * font using it carries no charset bytes at all and a reader without the table
 * cannot name its glyphs.
 */
static const uint16_t gfnt_cff_expert_charset[GFNT_CFF_EXPERT_CHARSET_COUNT] = {
    0,   1, 229, 230, 231, 232, 233, 234, // 0-7
  235, 236, 237, 238,  13,  14,  15,  99, // 8-15
  239, 240, 241, 242, 243, 244, 245, 246, // 16-23
  247, 248,  27,  28, 249, 250, 251, 252, // 24-31
  253, 254, 255, 256, 257, 258, 259, 260, // 32-39
  261, 262, 263, 264, 265, 266, 109, 110, // 40-47
  267, 268, 269, 270, 271, 272, 273, 274, // 48-55
  275, 276, 277, 278, 279, 280, 281, 282, // 56-63
  283, 284, 285, 286, 287, 288, 289, 290, // 64-71
  291, 292, 293, 294, 295, 296, 297, 298, // 72-79
  299, 300, 301, 302, 303, 304, 305, 306, // 80-87
  307, 308, 309, 310, 311, 312, 313, 314, // 88-95
  315, 316, 317, 318, 158, 155, 163, 319, // 96-103
  320, 321, 322, 323, 324, 325, 326, 150, // 104-111
  164, 169, 327, 328, 329, 330, 331, 332, // 112-119
  333, 334, 335, 336, 337, 338, 339, 340, // 120-127
  341, 342, 343, 344, 345, 346, 347, 348, // 128-135
  349, 350, 351, 352, 353, 354, 355, 356, // 136-143
  357, 358, 359, 360, 361, 362, 363, 364, // 144-151
  365, 366, 367, 368, 369, 370, 371, 372, // 152-159
  373, 374, 375, 376, 377, 378, // 160-165
};

/** @brief How many glyphs the expertsubset charset names. */
#define GFNT_CFF_EXPERT_SUBSET_CHARSET_COUNT 87

/**
 * @brief Predefined charset 2: the Expert Subset charset.
 *
 * A `charset` offset of 2 **is** this table rather than pointing at one, so a
 * font using it carries no charset bytes at all and a reader without the table
 * cannot name its glyphs.
 */
static const uint16_t gfnt_cff_expert_subset_charset[GFNT_CFF_EXPERT_SUBSET_CHARSET_COUNT] = {
    0,   1, 231, 232, 235, 236, 237, 238, // 0-7
   13,  14,  15,  99, 239, 240, 241, 242, // 8-15
  243, 244, 245, 246, 247, 248,  27,  28, // 16-23
  249, 250, 251, 253, 254, 255, 256, 257, // 24-31
  258, 259, 260, 261, 262, 263, 264, 265, // 32-39
  266, 109, 110, 267, 268, 269, 270, 272, // 40-47
  300, 301, 302, 305, 314, 315, 158, 155, // 48-55
  163, 320, 321, 322, 323, 324, 325, 326, // 56-63
  150, 164, 169, 327, 328, 329, 330, 331, // 64-71
  332, 333, 334, 335, 336, 337, 338, 339, // 72-79
  340, 341, 342, 343, 344, 345, 346, // 80-86
};

#endif // GHOTI_IO_GFNT_CFF_STRINGS_H
